# Generated by Django 2.2.24 on 2022-04-22 18:35

from django.db import migrations

import phonenumbers


def remake_phone(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        parsed_phonenumber = phonenumbers.parse(flat.owners_phonenumber, 'RU')
        if phonenumbers.is_valid_number(parsed_phonenumber):
            flat.owner_pure_phone = phonenumbers.format_number(
                parsed_phonenumber,
                phonenumbers.PhoneNumberFormat.E164
            )
            flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_flat_owner_pure_phone'),
    ]

    operations = [
        migrations.RunPython(remake_phone)
    ]
