# Generated by Django 2.2.24 on 2022-04-23 12:47

from django.db import migrations


def move_owner_info(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    flats = Flat.objects.all()
    for flat in flats.iterator():
        Owner.objects.get_or_create(
            full_name=flat.owner,
            phonenumber=flat.owners_phonenumber,
            pure_phone=flat.owner_pure_phone
        )


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_auto_20220423_1528'),
    ]

    operations = [
        migrations.RunPython(move_owner_info)
    ]
