# Generated by Django 2.2.24 on 2022-04-23 13:55

from django.db import migrations


def link_flats_and_owners(apps, scheme_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    owners = Owner.objects.all()
    for owner in owners.iterator():
        flats = Flat.objects.filter(
            owner=owner.full_name,
            owner_pure_phone=owner.pure_phone
        )
        owner.flats.set(flats)
    

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_auto_20220423_1547'),
    ]

    operations = [
        migrations.RunPython(link_flats_and_owners)
    ]

